<a href="https://colab.research.google.com/github/jhk0530/spider/blob/master/71_%EC%9C%A0%EC%82%AC_%EC%9D%B4%EB%AF%B8%EC%A7%80_%EA%B2%80%EC%B6%9C%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 이미지 인식 - Average Hash

`Average Hash`란, 이미지를 비교 가능한 해시 값으로 나타내는것, 해시함수 `MD5`, `SHA256`등을 이용하여 변환.

그러나 이미지가 비슷한지 검출할때는 사용하면 안됨 이유는 이미지데이터에

- 해상도 조절
- 색 보정
- PNG 등 형식 변경등으로 인해

완전한 바이너리를 찾는것이 어려움.

이로 인해 이미지가 조금 밝게 혹은 어둡게처럼 약간 변경후에도 이미지를 비교 할 경우 `Average Hash`를 사용함

예시 프로세스 과정

- 이미지를 8x8 사이즈로 축소 시킴
- 색을 그레이스케일로 변환
- 이미지의 각 픽셀의 평균을 계산하여 평균보다 크면 1, 작으면 0을 반환 

이렇게 하면 이미지마다 64비트의 해시 값을 구할 수 있음.

사용하는 library는 `pillow`






In [0]:
!pip3 install Pillow



In [0]:
# 파일 다운로드

import urllib.request

url = 'https://yotsuya.hotelkeihan.co.jp/wp-content/uploads/sites/394/2019/02/Tokyo-Tower-500x250.jpg'

savename  ='tower.jpg'
urllib.request.urlretrieve(url, savename)

print('저장되었습니다...!')


저장되었습니다...!


In [0]:
from PIL import Image
import numpy as np

def average_hash (fname, size = 16):
  img = Image.open(fname)
  img = img.convert('L') # 그레이 스케일로 변환
  img = img.resize((size,size), Image.ANTIALIAS) # 리사이즈
  
  pixel_data = img.getdata() # 픽셀값
  pixels = np.array(pixel_data) # numpy로 치환
  pixels = pixels.reshape((size, size)) # 2 차원으로 변환

  avg = pixels.mean()
  diff = 1* (pixels>avg)

  return diff

def np2hash(ahash):
  bhash  =[]
  
  for nl in ahash.tolist():
    s1 = [str(i) for i in nl]
    s2 = ''.join(s1)
    i = int(s2,2)
    bhash.append('%04x' % i)
  
  return "".join(bhash)

ahash = average_hash('tower.jpg')
print(ahash)
print(np2hash(ahash))


[[0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]]
0380038007c00780038007c006400f600f210f01060305070d0701170d1f0f0f


In [14]:
# CALTECH Data URL = http://www.vision.caltech.edu/Image_datasets/Caltech101/Caltech101.html

# http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz


import os

os.getcwd() # /content

#import urllib.request

#url = 'http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz'

#savename  ='101_ObjectCategories.tar.gz'
#urllib.request.urlretrieve(url, savename)

# print('저장되었습니다...!')


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-0e1fc10ab548>", line 5, in <module>
    os.getcwd() # /content
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/I

FileNotFoundError: ignored

데이터 저장하려는데 디렉토리 구조가 안보임 ㅅㄱ
